apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-object-detection-secret-3 
  description: Secure Supply Chain Example for Object Detection Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-object-detection-secret-3  
    janus-idp.io/tekton: test-object-detection-secret-3 
    backstage.io/kubernetes-id: test-object-detection-secret-3 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: tpetkos/test-object-detection-secret-3
  tags: ["ai", "detr", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 